version: '3.7'

services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=wrd-counter
    ports:
      - 3306:3306
    restart: always
  worker:
    container_name: worker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/wrd-counter?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
    restart: always
    depends_on:
      - db
      - core
  core:
    container_name: core
    build:
      context: https://github.com/Sander-N/wrd-counter-core.git#main:wrd-counter
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/wrd-counter?createDatabaseIfNotExist=true
    restart: always
    depends_on:
      - db